on:
  schedule:
    - cron:  '0 10 * * *'
  issue_comment:
    types: [created, edited]
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/SAP/styleguides/git/refs/heads/master | \
          jq -r ".object.sha" > latest_commit.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Steffen Buehl'
          git config --global user.email 'sb@sbuehl.com'
          git remote set-url origin https://x-access-token:${{ secrets.REPO_SCOPED_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git clone "https://github.com/SAP/styleguides" styleguides
          mkdir tmp
          find styleguides/clean-abap \( -name "*.md" \) -exec cp --parents {} tmp \;
          cp -a tmp/styleguides/clean-abap/* docs/
          mv docs/CleanABAP.md docs/index.md
          git add .          
          git commit -am "New release version"
          git push
